"""profile_picture room

Revision ID: 7baa36763667
Revises: e4e34d371b4d
Create Date: 2023-11-29 11:58:47.371662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7baa36763667'
down_revision = 'e4e34d371b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_room_profile_picture'), ['profile_picture'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_profile_picture'))
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
